project_name: devbox
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/devbox/main.go
    binary: devbox
    mod_timestamp: "{{ .CommitTimestamp }}" # For reproducible builds
    ldflags:
      - -s -w -X go.jetpack.io/devbox/internal/build.Version={{.Version}}
      - -s -w -X go.jetpack.io/devbox/internal/build.Commit={{.Commit}}
      - -s -w -X go.jetpack.io/devbox/internal/build.CommitDate={{.CommitDate}}
      - -s -w -X go.jetpack.io/devbox/internal/build.SentryDSN={{ .Env.SENTRY_DSN }}
      - -s -w -X go.jetpack.io/devbox/internal/build.TelemetryKey={{ .Env.TELEMETRY_KEY }}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
archives:
  - files:
      - no-files-will-match-* # Glob that does not match to create archive with only binaries.
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  prerelease: auto
  draft: true
  github:
    owner: devholic
    name: devbox
